# Generated by Django 2.2.1 on 2019-05-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='col',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
