# Generated by Django 2.2.1 on 2019-05-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190522_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='str_col',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
