# Generated by Django 2.2.1 on 2019-05-25 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_ticket_str_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='str_col',
        ),
    ]
