# Generated by Django 2.2.1 on 2019-05-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_ticket_sale_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(default=1, upload_to='logo/'),
        ),
    ]
